### ISSUE TITLE
Image create with only height param won't get ratio anymore

### ISSUE THREAD

**Issue by zeearth** [scaleflex/cloudimage-responsive-utils#3]
Hi, 

since the update of this package, all images display with react-cloudimage-responsive with only params height defined are no more resize. Is that a choice or a bug ? If it's a choice the documentation of react-cloudimage-responsive should be updated :

> height
> Type: String (e.g. 300px, 20vh) | Default: undefined
> If it's set, the plugin will use height as fixed value and change only according to the device pixel ratio.

With the new version of cloudimage-responsibe-utils, the function getRatio need width and height or return null for ratio.
May be this line : https://github.com/scaleflex/cloudimage-responsive-utils/blob/master/src/utils/get-ratio.js#L15

our code : 
` const img2 = <Img
    className="page-picture  -article"
    src="maman-et-bebe-idf.jpg"
    height={660}
  />`

here is image before the update of the package
![image_before_update](https://user-images.githubusercontent.com/1954929/126141921-f1101f80-4e09-4f15-8fcd-c90161270359.png)

And here image after the update
![image_after_update](https://user-images.githubusercontent.com/1954929/126142003-53333a2d-2da6-429a-a755-e62bd5d68b2d.png)

So should we pass a width param for all our image or do you an other proposition ?

Best resgards.

**Comment by dzmitry-stramavus** [comment]
hey @zeearth , checking

**Comment by dzmitry-stramavus** [comment]
@zeearth , we still return ratio https://github.com/scaleflex/cloudimage-responsive-utils/blob/master/src/utils/get-ratio.js#L15

but the problem with calculating height for images, checking and fixing (ETA few hours)

**Comment by dzmitry-stramavus** [comment]
@zeearth , fixed in https://github.com/scaleflex/react-cloudimage-responsive/releases/tag/v3.4.0

need to update react-cloudimage-responsive itself, it was done for JS versions but need to update all. Can you pls confirm that it's fixed for you?

**Comment by zeearth** [comment]
Thanks for the quick fix !!
All is good by passing only the height params. 

we just need to run npm install throttle-debounce
just after the update.

Sorry too put the issue on the bad composent but the diff was cloudimage-responsive-utils ;)

@dzmitry-stramavus do you need I close this issue or you will doing it ?
